stages:
  - test
  - build
  - deploy

.test project: 
  stage: test
  image: node:19
  script: 
      - npm install
      - npm run test

build project: 
  stage: build
  image: node:19
  script: 
      - npm install
      - npm run build
  artifacts: 
    paths: 
      - build/


netlify:
  stage: deploy
  image: node:19
  script: 
      - npm install -g netlify-cli
      - netlify deploy --dir=build --prod

