stages:
  - test
  - build
  - deploy

.test project: 
  stage: test
  image: node:19
  script: 
      - npm install
      - npm run test

build project: 
  stage: build
  image: node:19
  script: 
      - npm install
      - npm run build
  artifacts: 
    paths: 
      - dist/


netlify:
  stage: deploy
  image: node:19
  script:
    - npm install -g netlify-cli
    - netlify env:set VITE_RAPID_API_ARTICLE_KEY "$(cat .env | grep VITE_RAPID_API_ARTICLE_KEY | cut -d '=' -f2-)"
    - netlify deploy --dir=dist --prod

