stages:
  - test
  - build
  - deploy
  - push-to-github

.test project: 
  stage: test
  image: node:19
  script: 
      - npm install
      - npm run test

build project: 
  stage: build
  image: node:19
  script: 
      - npm install
      - npm run build
  artifacts: 
    paths: 
      - dist/

netlify:
  stage: deploy
  image: node:19
  script:
    - npm install -g netlify-cli
    - netlify env:set VITE_RAPID_API_ARTICLE_KEY "$VITE_RAPID_API_ARTICLE_KEY"
    - netlify deploy --dir=dist --prod


push to github:
  stage: push-to-github
  image: alpine/git
  script:
    # Check if the repository already exists
    - if [ ! -d "AI-Summarizer" ]; then git clone https://github.com/BenedictCodesHere/AI-Summarizer.git; fi
    - cd AI-Summarizer
    - rm -rf *
    - cp -r ./* .
    - git add .
    - git commit -m "deploy to Github from Gitlab"
    - git push origin master

